// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var IncomingMessage = /* module */[];

var ServerResponse = /* module */[];

var Server = /* module */[];

exports.IncomingMessage = IncomingMessage;
exports.ServerResponse = ServerResponse;
exports.Server = Server;
/* No side effect */
