// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var FutureJs = require("@qwick/future/src/FutureJs.bs.js");

function make(service, request, response) {
  return FutureJs.resultToPromise(Curry._2(service, request, response));
}

exports.make = make;
/* No side effect */
