// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function make(prim) {
  return {
          type: prim
        };
}

var Options = /* module */[/* make */make];

function option(string, options) {
  return (function (param) {
      return string.option(options, param);
    });
}

exports.Options = Options;
exports.option = option;
/* No side effect */
